### ISSUE TITLE
build on linux

### ISSUE THREAD

**Issue by sparkblaze** [rokett/Alertmanager-Forwarder#5]
```
go get github.com/rokett/alertmanager-forwader
go build
alertmanager-forwarder --graylog-url http://graylog.domain.tld --graylog-port 12201 --debug
```

Alert Manager starts and binds to the default port (10001) but doesn't seem to do anything.

```
I: 16:49:21 Starting Alertmanager-Forwarder.  Version .  Build .

Listening on port :10001
```

Firing events via REST client at /graylog don't appear in graylog or show anything in the console logs.

**Comment by rokett** [comment]
I'm not really sure what is wrong there, but I've never tested it on Linux; there shouldn't be anything which is OS specific though.

Let's work through it in the morning....I'm sure we can sort it out.

**Comment by rokett** [comment]
I've lost track somewhat.....do we still need this to work on Linux?  There's no reason it shouldn't, so probably won't take much to sort out if we do need it.
